### ISSUE TITLE
Yum support for Ubuntu?

### ISSUE THREAD

**Issue by karnauskas** [ibm-messaging/mq-chef#1]
Which distributions are actually supported?

**Comment by arthurbarr** [comment]
Nothing is officially "supported", but we are very happy to look at issues raised on GitHub.  At the moment we've only tested on Ubuntu 14.04 - this is an official MQ platform, and yes, MQ uses RPMs on every Linux distribution.  This is why we've gone down the Yum route, even though it's a bit unnatural on Ubuntu.

We'd like to test on more platforms over time - please let us know which ones you're interested in, and any that you've tried yourself.
